from odoo import api, fields, models

from .bolli_constants import BOLLI_FIELD_INDEXES, BOLLI_PANEL_ROWS


def _bolli_depends():
    names = []
    for index in BOLLI_FIELD_INDEXES:
        names.extend([
            f'g{index}',
            f'sotto{index}',
            f'sopra{index}',
            'boli_product_id',
        ])
    return names


class SaleOrderBolli(models.Model):
    _inherit = 'sale.order'

    high_vehicle = fields.Boolean(string='Veicolo Alto')
    prep_vehicle = fields.Boolean(string='Prep. Veicolo')
    prep_repair = fields.Boolean(string='Prep Riparazione')
    vehicle_type0 = fields.Boolean(string='Moto')
    vehicle_type1 = fields.Boolean(string='City car')
    vehicle_type2 = fields.Boolean(string='Berlina')
    vehicle_type3 = fields.Boolean(string='Monovolume')
    vehicle_type4 = fields.Boolean(string='Furgone')
    tot_bolli = fields.Float(string='Tot Bolli', compute='_compute_bolli_matrix', store=True)
    g1 = fields.Boolean(string='G1')
    a1 = fields.Boolean(string='A1')
    p1 = fields.Boolean(string='P1')
    mm_1 = fields.Boolean(string='Mm 1')
    sotto1 = fields.Integer(string='Sotto1', default=0)
    sopra1 = fields.Integer(string='Sopra1', default=0)
    ore1 = fields.Char(string='Ore1')
    ore_1 = fields.Char(string='Ore 1')
    g_c_1 = fields.Boolean(string='G C 1', compute='_compute_bolli_matrix', store=True)
    bolli1 = fields.Integer(string='Bolli1', compute='_compute_bolli_matrix', store=True)
    g2 = fields.Boolean(string='G2')
    a2 = fields.Boolean(string='A2')
    p2 = fields.Boolean(string='P2')
    mm_2 = fields.Boolean(string='Mm 2')
    sotto2 = fields.Integer(string='Sotto2', default=0)
    sopra2 = fields.Integer(string='Sopra2', default=0)
    ore2 = fields.Char(string='Ore2')
    ore_2 = fields.Char(string='Ore 2')
    g_c_2 = fields.Boolean(string='G C 2', compute='_compute_bolli_matrix', store=True)
    bolli2 = fields.Integer(string='Bolli2', compute='_compute_bolli_matrix', store=True)
    g3 = fields.Boolean(string='G3')
    a3 = fields.Boolean(string='A3')
    p3 = fields.Boolean(string='P3')
    mm_3 = fields.Boolean(string='Mm 3')
    sotto3 = fields.Integer(string='Sotto3', default=0)
    sopra3 = fields.Integer(string='Sopra3', default=0)
    ore3 = fields.Char(string='Ore3')
    ore_3 = fields.Char(string='Ore 3')
    g_c_3 = fields.Boolean(string='G C 3', compute='_compute_bolli_matrix', store=True)
    bolli3 = fields.Integer(string='Bolli3', compute='_compute_bolli_matrix', store=True)
    g4 = fields.Boolean(string='G4')
    a4 = fields.Boolean(string='A4')
    p4 = fields.Boolean(string='P4')
    mm_4 = fields.Boolean(string='Mm 4')
    sotto4 = fields.Integer(string='Sotto4', default=0)
    sopra4 = fields.Integer(string='Sopra4', default=0)
    ore4 = fields.Char(string='Ore4')
    ore_4 = fields.Char(string='Ore 4')
    g_c_4 = fields.Boolean(string='G C 4', compute='_compute_bolli_matrix', store=True)
    bolli4 = fields.Integer(string='Bolli4', compute='_compute_bolli_matrix', store=True)
    g5 = fields.Boolean(string='G5')
    a5 = fields.Boolean(string='A5')
    p5 = fields.Boolean(string='P5')
    mm_5 = fields.Boolean(string='Mm 5')
    sotto5 = fields.Integer(string='Sotto5', default=0)
    sopra5 = fields.Integer(string='Sopra5', default=0)
    ore5 = fields.Char(string='Ore5')
    ore_5 = fields.Char(string='Ore 5')
    g_c_5 = fields.Boolean(string='G C 5', compute='_compute_bolli_matrix', store=True)
    bolli5 = fields.Integer(string='Bolli5', compute='_compute_bolli_matrix', store=True)
    g6 = fields.Boolean(string='G6')
    a6 = fields.Boolean(string='A6')
    p6 = fields.Boolean(string='P6')
    mm_6 = fields.Boolean(string='Mm 6')
    sotto6 = fields.Integer(string='Sotto6', default=0)
    sopra6 = fields.Integer(string='Sopra6', default=0)
    ore6 = fields.Char(string='Ore6')
    ore_6 = fields.Char(string='Ore 6')
    g_c_6 = fields.Boolean(string='G C 6', compute='_compute_bolli_matrix', store=True)
    bolli6 = fields.Integer(string='Bolli6', compute='_compute_bolli_matrix', store=True)
    g7 = fields.Boolean(string='G7')
    a7 = fields.Boolean(string='A7')
    p7 = fields.Boolean(string='P7')
    mm_7 = fields.Boolean(string='Mm 7')
    sotto7 = fields.Integer(string='Sotto7', default=0)
    sopra7 = fields.Integer(string='Sopra7', default=0)
    ore7 = fields.Char(string='Ore7')
    ore_7 = fields.Char(string='Ore 7')
    g_c_7 = fields.Boolean(string='G C 7', compute='_compute_bolli_matrix', store=True)
    bolli7 = fields.Integer(string='Bolli7', compute='_compute_bolli_matrix', store=True)
    g8 = fields.Boolean(string='G8')
    a8 = fields.Boolean(string='A8')
    p8 = fields.Boolean(string='P8')
    mm_8 = fields.Boolean(string='Mm 8')
    sotto8 = fields.Integer(string='Sotto8', default=0)
    sopra8 = fields.Integer(string='Sopra8', default=0)
    ore8 = fields.Char(string='Ore8')
    ore_8 = fields.Char(string='Ore 8')
    g_c_8 = fields.Boolean(string='G C 8', compute='_compute_bolli_matrix', store=True)
    bolli8 = fields.Integer(string='Bolli8', compute='_compute_bolli_matrix', store=True)
    g9 = fields.Boolean(string='G9')
    a9 = fields.Boolean(string='A9')
    p9 = fields.Boolean(string='P9')
    mm_9 = fields.Boolean(string='Mm 9')
    sotto9 = fields.Integer(string='Sotto9', default=0)
    sopra9 = fields.Integer(string='Sopra9', default=0)
    ore9 = fields.Char(string='Ore9')
    ore_9 = fields.Char(string='Ore 9')
    g_c_9 = fields.Boolean(string='G C 9', compute='_compute_bolli_matrix', store=True)
    bolli9 = fields.Integer(string='Bolli9', compute='_compute_bolli_matrix', store=True)
    g10 = fields.Boolean(string='G10')
    a10 = fields.Boolean(string='A10')
    p10 = fields.Boolean(string='P10')
    mm_10 = fields.Boolean(string='Mm 10')
    sotto10 = fields.Integer(string='Sotto10', default=0)
    sopra10 = fields.Integer(string='Sopra10', default=0)
    ore10 = fields.Char(string='Ore10')
    ore_10 = fields.Char(string='Ore 10')
    g_c_10 = fields.Boolean(string='G C 10', compute='_compute_bolli_matrix', store=True)
    bolli10 = fields.Integer(string='Bolli10', compute='_compute_bolli_matrix', store=True)
    g12 = fields.Boolean(string='G12')
    a12 = fields.Boolean(string='A12')
    p12 = fields.Boolean(string='P12')
    mm_12 = fields.Boolean(string='Mm 12')
    sotto12 = fields.Integer(string='Sotto12', default=0)
    sopra12 = fields.Integer(string='Sopra12', default=0)
    ore12 = fields.Char(string='Ore12')
    ore_12 = fields.Char(string='Ore 12')
    g_c_12 = fields.Boolean(string='G C 12', compute='_compute_bolli_matrix', store=True)
    bolli12 = fields.Integer(string='Bolli12', compute='_compute_bolli_matrix', store=True)
    g13 = fields.Boolean(string='G13')
    a13 = fields.Boolean(string='A13')
    p13 = fields.Boolean(string='P13')
    mm_13 = fields.Boolean(string='Mm 13')
    sotto13 = fields.Integer(string='Sotto13', default=0)
    sopra13 = fields.Integer(string='Sopra13', default=0)
    ore13 = fields.Char(string='Ore13')
    ore_13 = fields.Char(string='Ore 13')
    g_c_13 = fields.Boolean(string='G C 13', compute='_compute_bolli_matrix', store=True)
    bolli13 = fields.Integer(string='Bolli13', compute='_compute_bolli_matrix', store=True)
    g14 = fields.Boolean(string='G14')
    a14 = fields.Boolean(string='A14')
    p14 = fields.Boolean(string='P14')
    mm_14 = fields.Boolean(string='Mm 14')
    sotto14 = fields.Integer(string='Sotto14', default=0)
    sopra14 = fields.Integer(string='Sopra14', default=0)
    ore14 = fields.Char(string='Ore14')
    ore_14 = fields.Char(string='Ore 14')
    g_c_14 = fields.Boolean(string='G C 14', compute='_compute_bolli_matrix', store=True)
    bolli14 = fields.Integer(string='Bolli14', compute='_compute_bolli_matrix', store=True)
    g15 = fields.Boolean(string='G15')
    a15 = fields.Boolean(string='A15')
    p15 = fields.Boolean(string='P15')
    mm_15 = fields.Boolean(string='Mm 15')
    sotto15 = fields.Integer(string='Sotto15', default=0)
    sopra15 = fields.Integer(string='Sopra15', default=0)
    ore15 = fields.Char(string='Ore15')
    ore_15 = fields.Char(string='Ore 15')
    g_c_15 = fields.Boolean(string='G C 15', compute='_compute_bolli_matrix', store=True)
    bolli15 = fields.Integer(string='Bolli15', compute='_compute_bolli_matrix', store=True)
    g16 = fields.Boolean(string='G16')
    a16 = fields.Boolean(string='A16')
    p16 = fields.Boolean(string='P16')
    mm_16 = fields.Boolean(string='Mm 16')
    sotto16 = fields.Integer(string='Sotto16', default=0)
    sopra16 = fields.Integer(string='Sopra16', default=0)
    ore16 = fields.Char(string='Ore16')
    ore_16 = fields.Char(string='Ore 16')
    g_c_16 = fields.Boolean(string='G C 16', compute='_compute_bolli_matrix', store=True)
    bolli16 = fields.Integer(string='Bolli16', compute='_compute_bolli_matrix', store=True)
    g17 = fields.Boolean(string='G17')
    a17 = fields.Boolean(string='A17')
    p17 = fields.Boolean(string='P17')
    mm_17 = fields.Boolean(string='Mm 17')
    sotto17 = fields.Integer(string='Sotto17', default=0)
    sopra17 = fields.Integer(string='Sopra17', default=0)
    ore17 = fields.Char(string='Ore17')
    ore_17 = fields.Char(string='Ore 17')
    g_c_17 = fields.Boolean(string='G C 17', compute='_compute_bolli_matrix', store=True)
    bolli17 = fields.Integer(string='Bolli17', compute='_compute_bolli_matrix', store=True)
    g18 = fields.Boolean(string='G18')
    a18 = fields.Boolean(string='A18')
    p18 = fields.Boolean(string='P18')
    mm_18 = fields.Boolean(string='Mm 18')
    sotto18 = fields.Integer(string='Sotto18', default=0)
    sopra18 = fields.Integer(string='Sopra18', default=0)
    ore18 = fields.Char(string='Ore18')
    ore_18 = fields.Char(string='Ore 18')
    g_c_18 = fields.Boolean(string='G C 18', compute='_compute_bolli_matrix', store=True)
    bolli18 = fields.Integer(string='Bolli18', compute='_compute_bolli_matrix', store=True)

    @api.depends(*_bolli_depends())
    def _compute_bolli_matrix(self):
        for order in self:
            total = 0.0
            for index, _label in BOLLI_PANEL_ROWS:
                glue = order[f'g{index}']
                sotto = order[f'sotto{index}'] or 0
                sopra = order[f'sopra{index}'] or 0
                active = bool(glue and (sotto or sopra))
                order[f'g_c_{index}'] = active
                bolli = (sotto + sopra) if active else 0
                order[f'bolli{index}'] = bolli
                total += bolli
            order.tot_bolli = total

